packages:
  - apps/*
  - packages/*

allowedDeprecatedVersions:
  glob: 7.2.3
  inflight: 1.0.6

catalog:
  '@eslint/eslintrc': ^3.3.3
  '@eslint/js': ^9.39.1
  '@nestjs/cli': ^11.0.14
  '@nestjs/common': ^11.1.9
  '@nestjs/config': 4.0.2
  '@nestjs/core': ^11.1.9
  '@nestjs/jwt': 11.0.2
  '@nestjs/microservices': ^11.1.9
  '@nestjs/passport': ^11.0.5
  '@nestjs/platform-express': ^11.1.9
  '@nestjs/schematics': ^11.0.9
  '@nestjs/testing': ^11.1.9
  '@nestjs/typeorm': 11.0.0
  '@tailwindcss/vite': ^4.1.17
  '@tanstack/react-router': ^1.140.0
  '@tanstack/router-plugin': ^1.140.0
  '@types/bcrypt': ^6.0.0
  '@types/express': ^5.0.6
  '@types/jest': ^30.0.0
  '@types/node': ^24.10.1
  '@types/passport-jwt': ^4.0.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@types/supertest': ^6.0.3
  '@typescript-eslint/eslint-plugin': ^8.48.1
  '@typescript-eslint/parser': ^8.48.1
  '@vitejs/plugin-react': ^5.1.1
  amqp-connection-manager: ^5.0.0
  amqplib: ^0.10.9
  bcrypt: ^6.0.0
  class-transformer: 0.5.1
  class-validator: 0.14.3
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  eslint: ^9.39.1
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  globals: ^16.5.0
  jest: ^30.2.0
  joi: 18.0.2
  lucide-react: ^0.556.0
  passport: ^0.7.0
  passport-jwt: ^4.0.1
  pg: 8.16.3
  prettier: ^3.7.4
  react: ^19.2.1
  react-dom: ^19.2.1
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.2
  source-map-support: ^0.5.21
  supertest: ^7.1.4
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.17
  ts-jest: ^29.4.6
  ts-loader: ^9.5.4
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  turbo: ^2.6.3
  tw-animate-css: ^1.4.0
  typeorm: 0.3.28
  typescript: 5.9.3
  typescript-eslint: ^8.48.1
  vite: ^7.2.7
  zod: ^4.1.13

onlyBuiltDependencies:
  - '@nestjs/core'
  - esbuild
